# application.yml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trading_db?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
      show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 366788596555-tkpo870btmcs2ktdehm172s3fppu5m4p.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

#          microsoft:
#            client-id: ${MICROSOFT_CLIENT_ID}
#            client-secret: ${MICROSOFT_CLIENT_SECRET}
#            scope:
#              - openid
#              - profile
#              - email
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Microsoft
#
#        provider:
#          microsoft:
#            issuer-uri: https://login.microsoftonline.com/common/v2.0
#            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#            user-info-uri: https://graph.microsoft.com/oidc/userinfo
#            user-name-attribute: name

  # CORS configuration for frontend
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "*"
    allowed-headers: "*"
    allow-credentials: true

# JWT Configuration
jwt:
  secret: X4kNZ4P47gnbze0EeZL3cZXjmJUQuuf8U6JoyhjCliea7FutOS2Raq5GK1moULHCmG0e95Ll4qXczNCqAsHeeg==
  expiration-ms: 86400000

# App specific config
app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
  allowed-origins:
    - http://localhost:3000
    - https://your-production-domain.com

# Logging configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.yourpackage: DEBUG